### ISSUE TITLE
图片编辑框架1.2.4使用异常

### ISSUE THREAD

**Issue by timizhuoym** [miaowmiaow/fragmject#4]
![image](https://user-images.githubusercontent.com/24522660/135371712-a9b38c73-a51a-4cef-916a-c8866b8b7e26.png)

**Comment by timizhuoym** [comment]
android.util.AndroidRuntimeException: requestFeature() must be called before adding content
        at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:336)
        at android.app.Dialog.requestWindowFeature(Dialog.java:1152)
        at com.example.miaow.picture.dialog.PictureBaseDialog.onActivityCreated(PictureBaseDialog.kt:19)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2996)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by timizhuoym** [comment]
我是这样修复的
![image](https://user-images.githubusercontent.com/24522660/135377819-ea38290e-8008-4dda-9272-17b6b10114dc.png)
![image](https://user-images.githubusercontent.com/24522660/135377889-1390bdab-24c0-4692-89b3-9794c84364f3.png)

**Comment by miaowmiaow** [comment]
感谢你的反馈，我已经根据你的描述进行修复
